### PR TITLE
SquadMoveAndClearAction.uc: added new CSGrenadeDelayTime property

### LINKED ISSUE #105: AI officers should pause before entry after throwing CS
During an "open and CS" or "breach and CS" action, the AI officers will enter the room immediately after throwing the CS gas grenade. This doesn't give suspects enough time to succumb to the gas. AI should wait 1 - 2 seconds before entry.

### PR DESCRIPTION
**Pull request by kevinfoley**
Adds delay between AI officers throwing a CS grenade and actually entering the room, to give the CS more time to take effect. Closes #105

### CODE REVIEW

**Comment by jose21crisis** [comment]
This doesn't affect the Leader and Clear commands, or I think it doesn't affect them.

**Comment by kevinfoley** [comment]
@jose21crisis My testing shows that this is working with Move and Clear, Open and Clear, and Breach and Clear

**Comment by sandman332** [comment]
Yea but he was refering to it probably not working with the leader command.  So leader throw and clear, etc.  Leader ones.

**Comment by kevinfoley** [comment]
@sandman332  Apparently I'm not familiar with those. I'll look into it tonight or tomorrow.

**Comment by sandman332** [comment]
The commands are leader throw and clear.  Its used for when the player throws the grenade into the room, then the ai officers clear.  Instead of them throwing the grenade and clearing.

**Comment by kevinfoley** [comment]
@sandman332 Thanks, I hadn't realized that was an option. How do you access that in the game? Is it only available in certain modes?

**Comment by sandman332** [comment]
Same as you would do move and clear or open and clear.  Its one of the commands attached.

**Comment by kevinfoley** [comment]
@sandman332  I just added support for leader-throw-and-clear and breach-leader-throw-and-clear

**Pull request merged**
