### PR TITLE
Added new setting for skipping intro sequence

### PR DESCRIPTION
**Pull request by kevinfoley**
Normally, a campaign mission starts with a brief "cinematic" sequence consisting of black bars along the top and bottom edges of the screen, text of the address of the current mission in the bottom-left corner, and an audio clip from the Dispatcher. The player is not allowed to move during this period.

This update adds a new setting (to SwatGui.ini) called `SkipOpeningCinematic` that lets the player skip the opening cinematic and start moving immediately. The black bars appear but slide offscreen immediately, while the text does not appear and the Dispatcher audio does not play (the experience is therefore identical to when you start a Quick Mission). This feature is useful for impatient players who don't want to wait out the few seconds that the cinematic lasts each time they start a mission.

**Note:** I set `SkipOpeningCinematic` to `True` in this commit to demonstrate the feature, but it might be better for the default value to be `False`

### CODE REVIEW

**Comment by jose21crisis** [comment]
With this you can skip the cinematic while still hearing the Dispatcher?

**Comment by kevinfoley** [comment]
@jose21crisis It does not play the Dispatcher audio when it skips the opening cinematic. I didn't think about that. It might be possible to tweak it so that the dispatcher audio still plays. I'll look into that tonight or tomorrow.

**Comment by jose21crisis** [comment]
I say it because if it doesn't, then it is the exact same thing as the "Disable Dispatch Audio" option that eez already integrated.

**Comment by kevinfoley** [comment]
Well shoot, I guess I missed that one. I'll check it out later.

**Comment by kevinfoley** [comment]
Closed due to being a copy of an existing feature

**Pull request closed without merging**
