### PR TITLE
Mark with lightstick after clearing

### PR DESCRIPTION
**Pull request by kevinfoley**
Squad AI will automatically mark the entry doorway with a lightstick after clearing a room, to indicate that the room has been cleared. Confirmation voice-over for dropping the lightstick doesn't play when this occurs. This behavior is based on SWAT 3.

### CODE REVIEW

**Comment by theengineertcr** [comment]
Will try this to see for bugs

**Comment by theengineertcr** [comment]
Error in compilation. Line 89: Unrecognized member 'GetPlaySpeech' in class 'DropLightstickGoal'

**Comment by theengineertcr** [comment]
You haven't uploaded the updated DropLightStickGoal.uc which results in compilation errors.

**Comment by theengineertcr** [comment]
So far no bugs, SWATs take like 5 seconds before thinking of deploying lightstick, lightstick still makes too loud of a noise on drop, alerting multiple suspects.

**Comment by kevinfoley** [comment]
Thanks. I agree they wait too long; maybe I can push it up in the execution order. With all the yelling that the team does when you order an enter and clear, the suspects should already be alert before they drop the lightstick. If the lightstick is too loud, that's a separate bug.

**Comment by kevinfoley** [comment]
So the lightstick won't be deployed until each officer has finished the individual MoveAndClearAction that was assigned to him. The issue is probably within MoveAndClearAction: after they say "all clear", they are programmed to wait between `MinHoldClearPositionTime` and `MaxHoldClearPositionTime`, and _then_ wait for 'kClearedRoomUpdateTime', before the action/goal are marked as complete. I'm guessing these two delays add up to the 3 - 5 seconds they seem to wait before the lightstick.

The delays are probably in case they called out "clear" prematurely and there's actually a suspect hiding behind something, but the end result is that they just stand around doing nothing for several seconds. It might be worth seeing how it would impact the gameplay if we cut down on these delays.

**Comment by kevinfoley** [comment]
I reduced the delay significantly, since it doesn't seem to have much functional purpose. Now they will mark with a lightstick within a few seconds of clearing the room.

**Comment by sandman332** [comment]
Tested this, seems to be bugged.  Officers will drop the lightstick, but it's not there.  It doesn't even drop, as soon as they play the animation for dropping one, it doesn't even spawn in their hand or nothing.

**Comment by eezstreet** [comment]
This code has been pulled into a new branch, `v6`

**Pull request closed without merging**
