### PR TITLE
Iron sights improvements

### PR DESCRIPTION
**Pull request by kevinfoley**
I could have sworn I already did a PR for these.

- Iron sight animation now tweens rotation as well as position 
- Set up new property that can be used for animation spline points 
- Hands: better method of getting deltaTime, to fix new jitter caused by 07a6a9d

### CODE REVIEW

**Comment by eezstreet** [comment]
It already got merged (see #207)

**Comment by kevinfoley** [comment]
@eezstreet You marked the previous PR as closed, but these commits are not present in the iron-sights branch. Maybe a GitHub bug? See https://github.com/eezstreet/SWATEliteForce/commits/iron-sights . Also notice that both PRs show "closed with unmerged commits" at the bottom.

**Comment by kevinfoley** [comment]
Maybe you merged in your local copy but forgot to push?

**Comment by eezstreet** [comment]
I forgot to push the commits, they were on my local copy. Check out that branch now.

**Pull request closed without merging**
